set_property PACKAGE_PIN AJ23 [get_ports spi0_clk_o]
set_property PACKAGE_PIN AJ24 [get_ports spi0_sdo_o]
set_property PACKAGE_PIN AF19 [get_ports spi0_sdi_i]
set_property PACKAGE_PIN AE21 [get_ports spi0_csn_0_o]
set_property PACKAGE_PIN AD21 [get_ports spi0_csn_1_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_clk_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_sdo_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_sdi_i]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_csn_0_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_csn_1_o]
set_property PACKAGE_PIN AA15 [get_ports spi1_clk_o]
set_property PACKAGE_PIN AA14 [get_ports spi1_sdo_o]
set_property PACKAGE_PIN AD14 [get_ports spi1_sdi_i]
set_property PACKAGE_PIN AH13 [get_ports spi1_csn_0_o]
set_property PACKAGE_PIN AH14 [get_ports spi1_csn_1_o]

set_property IOSTANDARD LVCMOS25 [get_ports spi1_sdo_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_sdi_i]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_clk_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_csn_0_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_csn_1_o]
set_property PACKAGE_PIN AJ20 [get_ports fr9009_0_rst]
set_property PACKAGE_PIN R28 [get_ports ad9528_0_rst]
set_property PACKAGE_PIN AJ15 [get_ports fr9009_1_rst]
set_property PACKAGE_PIN AJ30 [get_ports ad9528_1_rst]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_0_rst]
set_property IOSTANDARD LVCMOS25 [get_ports ad9528_0_rst]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_1_rst]
set_property IOSTANDARD LVCMOS25 [get_ports ad9528_1_rst]
set_property PACKAGE_PIN T28 [get_ports ad9528_sysref_req]
set_property IOSTANDARD LVCMOS25 [get_ports ad9528_sysref_req]

set_property PACKAGE_PIN Y22 [get_ports fr9009_gpio_0]
set_property PACKAGE_PIN AB15 [get_ports fr9009_gpio_1]
set_property PACKAGE_PIN AA24 [get_ports fr9009_gpio_2]
set_property PACKAGE_PIN AB24 [get_ports fr9009_gpio_3]

set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_0]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_1]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_2]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_3]


set_property PACKAGE_PIN AA8 [get_ports gt_clk_i_p]
set_property PACKAGE_PIN AH19 [get_ports rx0_sync_o_p]
# set_property PACKAGE_PIN AG12 [get_ports rx1_sync_o_p]
set_property PACKAGE_PIN AF20 [get_ports sysref_i_p]
set_property PACKAGE_PIN AK17 [get_ports tx0_sync_i_p]
# set_property PACKAGE_PIN AE12 [get_ports tx1_sync_i_p]
set_property IOSTANDARD LVDS_25 [get_ports sysref_i_p]
set_property IOSTANDARD LVDS_25 [get_ports rx0_sync_o_p]
# set_property IOSTANDARD LVDS_25 [get_ports rx1_sync_o_p]
set_property IOSTANDARD LVDS_25 [get_ports tx0_sync_i_p]
# set_property IOSTANDARD LVDS_25 [get_ports tx1_sync_i_p]
# set_property PACKAGE_PIN AJ8 [get_ports {rxp_in_0[0]}]
# set_property PACKAGE_PIN AC4 [get_ports {rxp_in_1[0]}]
set_property PACKAGE_PIN AJ8 [get_ports {rxp_in_0[0]}]
set_property PACKAGE_PIN AG8 [get_ports {rxp_in_0[1]}]
set_property PACKAGE_PIN AH10 [get_ports {rxp_in_0[2]}]
set_property PACKAGE_PIN AE8 [get_ports {rxp_in_0[3]}]


create_clock -period 4.000 -name gt_clk_i_p -waveform {0.000 2.000} [get_ports gt_clk_i_p]





create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_jesd_clk/core_clk_o]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {rx_lane_0[0]} {rx_lane_0[1]} {rx_lane_0[2]} {rx_lane_0[3]} {rx_lane_0[4]} {rx_lane_0[5]} {rx_lane_0[6]} {rx_lane_0[7]} {rx_lane_0[8]} {rx_lane_0[9]} {rx_lane_0[10]} {rx_lane_0[11]} {rx_lane_0[12]} {rx_lane_0[13]} {rx_lane_0[14]} {rx_lane_0[15]} {rx_lane_0[16]} {rx_lane_0[17]} {rx_lane_0[18]} {rx_lane_0[19]} {rx_lane_0[20]} {rx_lane_0[21]} {rx_lane_0[22]} {rx_lane_0[23]} {rx_lane_0[24]} {rx_lane_0[25]} {rx_lane_0[26]} {rx_lane_0[27]} {rx_lane_0[28]} {rx_lane_0[29]} {rx_lane_0[30]} {rx_lane_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {tx_start_of_multiframe_0[0]} {tx_start_of_multiframe_0[1]} {tx_start_of_multiframe_0[2]} {tx_start_of_multiframe_0[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {rx_lane_3[0]} {rx_lane_3[1]} {rx_lane_3[2]} {rx_lane_3[3]} {rx_lane_3[4]} {rx_lane_3[5]} {rx_lane_3[6]} {rx_lane_3[7]} {rx_lane_3[8]} {rx_lane_3[9]} {rx_lane_3[10]} {rx_lane_3[11]} {rx_lane_3[12]} {rx_lane_3[13]} {rx_lane_3[14]} {rx_lane_3[15]} {rx_lane_3[16]} {rx_lane_3[17]} {rx_lane_3[18]} {rx_lane_3[19]} {rx_lane_3[20]} {rx_lane_3[21]} {rx_lane_3[22]} {rx_lane_3[23]} {rx_lane_3[24]} {rx_lane_3[25]} {rx_lane_3[26]} {rx_lane_3[27]} {rx_lane_3[28]} {rx_lane_3[29]} {rx_lane_3[30]} {rx_lane_3[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {rx_lane_2[0]} {rx_lane_2[1]} {rx_lane_2[2]} {rx_lane_2[3]} {rx_lane_2[4]} {rx_lane_2[5]} {rx_lane_2[6]} {rx_lane_2[7]} {rx_lane_2[8]} {rx_lane_2[9]} {rx_lane_2[10]} {rx_lane_2[11]} {rx_lane_2[12]} {rx_lane_2[13]} {rx_lane_2[14]} {rx_lane_2[15]} {rx_lane_2[16]} {rx_lane_2[17]} {rx_lane_2[18]} {rx_lane_2[19]} {rx_lane_2[20]} {rx_lane_2[21]} {rx_lane_2[22]} {rx_lane_2[23]} {rx_lane_2[24]} {rx_lane_2[25]} {rx_lane_2[26]} {rx_lane_2[27]} {rx_lane_2[28]} {rx_lane_2[29]} {rx_lane_2[30]} {rx_lane_2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 64 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ddr_tdata[0]} {ddr_tdata[1]} {ddr_tdata[2]} {ddr_tdata[3]} {ddr_tdata[4]} {ddr_tdata[5]} {ddr_tdata[6]} {ddr_tdata[7]} {ddr_tdata[8]} {ddr_tdata[9]} {ddr_tdata[10]} {ddr_tdata[11]} {ddr_tdata[12]} {ddr_tdata[13]} {ddr_tdata[14]} {ddr_tdata[15]} {ddr_tdata[16]} {ddr_tdata[17]} {ddr_tdata[18]} {ddr_tdata[19]} {ddr_tdata[20]} {ddr_tdata[21]} {ddr_tdata[22]} {ddr_tdata[23]} {ddr_tdata[24]} {ddr_tdata[25]} {ddr_tdata[26]} {ddr_tdata[27]} {ddr_tdata[28]} {ddr_tdata[29]} {ddr_tdata[30]} {ddr_tdata[31]} {ddr_tdata[32]} {ddr_tdata[33]} {ddr_tdata[34]} {ddr_tdata[35]} {ddr_tdata[36]} {ddr_tdata[37]} {ddr_tdata[38]} {ddr_tdata[39]} {ddr_tdata[40]} {ddr_tdata[41]} {ddr_tdata[42]} {ddr_tdata[43]} {ddr_tdata[44]} {ddr_tdata[45]} {ddr_tdata[46]} {ddr_tdata[47]} {ddr_tdata[48]} {ddr_tdata[49]} {ddr_tdata[50]} {ddr_tdata[51]} {ddr_tdata[52]} {ddr_tdata[53]} {ddr_tdata[54]} {ddr_tdata[55]} {ddr_tdata[56]} {ddr_tdata[57]} {ddr_tdata[58]} {ddr_tdata[59]} {ddr_tdata[60]} {ddr_tdata[61]} {ddr_tdata[62]} {ddr_tdata[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {rx_start_of_multiframe_0[0]} {rx_start_of_multiframe_0[1]} {rx_start_of_multiframe_0[2]} {rx_start_of_multiframe_0[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 128 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {tx_tdata_0[0]} {tx_tdata_0[1]} {tx_tdata_0[2]} {tx_tdata_0[3]} {tx_tdata_0[4]} {tx_tdata_0[5]} {tx_tdata_0[6]} {tx_tdata_0[7]} {tx_tdata_0[8]} {tx_tdata_0[9]} {tx_tdata_0[10]} {tx_tdata_0[11]} {tx_tdata_0[12]} {tx_tdata_0[13]} {tx_tdata_0[14]} {tx_tdata_0[15]} {tx_tdata_0[16]} {tx_tdata_0[17]} {tx_tdata_0[18]} {tx_tdata_0[19]} {tx_tdata_0[20]} {tx_tdata_0[21]} {tx_tdata_0[22]} {tx_tdata_0[23]} {tx_tdata_0[24]} {tx_tdata_0[25]} {tx_tdata_0[26]} {tx_tdata_0[27]} {tx_tdata_0[28]} {tx_tdata_0[29]} {tx_tdata_0[30]} {tx_tdata_0[31]} {tx_tdata_0[32]} {tx_tdata_0[33]} {tx_tdata_0[34]} {tx_tdata_0[35]} {tx_tdata_0[36]} {tx_tdata_0[37]} {tx_tdata_0[38]} {tx_tdata_0[39]} {tx_tdata_0[40]} {tx_tdata_0[41]} {tx_tdata_0[42]} {tx_tdata_0[43]} {tx_tdata_0[44]} {tx_tdata_0[45]} {tx_tdata_0[46]} {tx_tdata_0[47]} {tx_tdata_0[48]} {tx_tdata_0[49]} {tx_tdata_0[50]} {tx_tdata_0[51]} {tx_tdata_0[52]} {tx_tdata_0[53]} {tx_tdata_0[54]} {tx_tdata_0[55]} {tx_tdata_0[56]} {tx_tdata_0[57]} {tx_tdata_0[58]} {tx_tdata_0[59]} {tx_tdata_0[60]} {tx_tdata_0[61]} {tx_tdata_0[62]} {tx_tdata_0[63]} {tx_tdata_0[64]} {tx_tdata_0[65]} {tx_tdata_0[66]} {tx_tdata_0[67]} {tx_tdata_0[68]} {tx_tdata_0[69]} {tx_tdata_0[70]} {tx_tdata_0[71]} {tx_tdata_0[72]} {tx_tdata_0[73]} {tx_tdata_0[74]} {tx_tdata_0[75]} {tx_tdata_0[76]} {tx_tdata_0[77]} {tx_tdata_0[78]} {tx_tdata_0[79]} {tx_tdata_0[80]} {tx_tdata_0[81]} {tx_tdata_0[82]} {tx_tdata_0[83]} {tx_tdata_0[84]} {tx_tdata_0[85]} {tx_tdata_0[86]} {tx_tdata_0[87]} {tx_tdata_0[88]} {tx_tdata_0[89]} {tx_tdata_0[90]} {tx_tdata_0[91]} {tx_tdata_0[92]} {tx_tdata_0[93]} {tx_tdata_0[94]} {tx_tdata_0[95]} {tx_tdata_0[96]} {tx_tdata_0[97]} {tx_tdata_0[98]} {tx_tdata_0[99]} {tx_tdata_0[100]} {tx_tdata_0[101]} {tx_tdata_0[102]} {tx_tdata_0[103]} {tx_tdata_0[104]} {tx_tdata_0[105]} {tx_tdata_0[106]} {tx_tdata_0[107]} {tx_tdata_0[108]} {tx_tdata_0[109]} {tx_tdata_0[110]} {tx_tdata_0[111]} {tx_tdata_0[112]} {tx_tdata_0[113]} {tx_tdata_0[114]} {tx_tdata_0[115]} {tx_tdata_0[116]} {tx_tdata_0[117]} {tx_tdata_0[118]} {tx_tdata_0[119]} {tx_tdata_0[120]} {tx_tdata_0[121]} {tx_tdata_0[122]} {tx_tdata_0[123]} {tx_tdata_0[124]} {tx_tdata_0[125]} {tx_tdata_0[126]} {tx_tdata_0[127]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {rx_lane_1[0]} {rx_lane_1[1]} {rx_lane_1[2]} {rx_lane_1[3]} {rx_lane_1[4]} {rx_lane_1[5]} {rx_lane_1[6]} {rx_lane_1[7]} {rx_lane_1[8]} {rx_lane_1[9]} {rx_lane_1[10]} {rx_lane_1[11]} {rx_lane_1[12]} {rx_lane_1[13]} {rx_lane_1[14]} {rx_lane_1[15]} {rx_lane_1[16]} {rx_lane_1[17]} {rx_lane_1[18]} {rx_lane_1[19]} {rx_lane_1[20]} {rx_lane_1[21]} {rx_lane_1[22]} {rx_lane_1[23]} {rx_lane_1[24]} {rx_lane_1[25]} {rx_lane_1[26]} {rx_lane_1[27]} {rx_lane_1[28]} {rx_lane_1[29]} {rx_lane_1[30]} {rx_lane_1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list ddr_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list rx_sync_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list rx_tvalid_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list sysref_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list tx_sync_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list tx_tready_0]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list u_system_wrapper/system_i/sys_ps7/inst/FCLK_CLK2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list fr9009_0_rst_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets core_clk]
