####################################################################################
## Copyright (c) 2026
## SPDX-License-Identifier: BSD-1-Clause
####################################################################################

PROJECT_NAME := fr9009_zc706_prj

M_DEPS += system_top.v
M_DEPS += jesd_clk.v
M_DEPS += system_constr.xdc

LIB_DEPS += axi_fr9009_config
LIB_DEPS += util_rx_data_capture
LIB_DEPS += util_tx_data_pack

include ../../scripts/project-xilinx.mk
