set_property PACKAGE_PIN AJ23 [get_ports spi0_clk_o]
set_property PACKAGE_PIN AJ24 [get_ports spi0_sdo_o]
set_property PACKAGE_PIN AF19 [get_ports spi0_sdi_i]
set_property PACKAGE_PIN AE21 [get_ports spi0_csn_0_o]
set_property PACKAGE_PIN AD21 [get_ports spi0_csn_1_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_clk_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_sdo_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_sdi_i]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_csn_0_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi0_csn_1_o]
set_property PACKAGE_PIN AA15 [get_ports spi1_clk_o]
set_property PACKAGE_PIN AA14 [get_ports spi1_sdo_o]
set_property PACKAGE_PIN AD14 [get_ports spi1_sdi_i]
set_property PACKAGE_PIN AH13 [get_ports spi1_csn_0_o]
set_property PACKAGE_PIN AH14 [get_ports spi1_csn_1_o]

set_property IOSTANDARD LVCMOS25 [get_ports spi1_sdo_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_sdi_i]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_clk_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_csn_0_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi1_csn_1_o]
set_property PACKAGE_PIN AJ20 [get_ports fr9009_0_rst]
set_property PACKAGE_PIN R28 [get_ports ad9528_0_rst]
#set_property PACKAGE_PIN AJ15 [get_ports fr9009_1_rst]
#set_property PACKAGE_PIN AJ30 [get_ports ad9528_1_rst]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_0_rst]
set_property IOSTANDARD LVCMOS25 [get_ports ad9528_0_rst]
#set_property IOSTANDARD LVCMOS25 [get_ports fr9009_1_rst]
#set_property IOSTANDARD LVCMOS25 [get_ports ad9528_1_rst]
set_property PACKAGE_PIN T28 [get_ports ad9528_sysref_req]
set_property IOSTANDARD LVCMOS25 [get_ports ad9528_sysref_req]

set_property PACKAGE_PIN Y22 [get_ports fr9009_gpio_0]
set_property PACKAGE_PIN AB15 [get_ports fr9009_gpio_1]
set_property PACKAGE_PIN AA24 [get_ports fr9009_gpio_2]
set_property PACKAGE_PIN AB24 [get_ports fr9009_gpio_3]

set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_0]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_1]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_2]
set_property IOSTANDARD LVCMOS25 [get_ports fr9009_gpio_3]


set_property PACKAGE_PIN AA8 [get_ports gt_clk_i_p]
set_property PACKAGE_PIN AH19 [get_ports rx0_sync_o_p]
# set_property PACKAGE_PIN AG12 [get_ports rx1_sync_o_p]
set_property PACKAGE_PIN AF20 [get_ports sysref_i_p]
set_property PACKAGE_PIN AK17 [get_ports tx0_sync_i_p]
# set_property PACKAGE_PIN AE12 [get_ports tx1_sync_i_p]
set_property IOSTANDARD LVDS_25 [get_ports sysref_i_p]
set_property IOSTANDARD LVDS_25 [get_ports rx0_sync_o_p]
# set_property IOSTANDARD LVDS_25 [get_ports rx1_sync_o_p]
set_property IOSTANDARD LVDS_25 [get_ports tx0_sync_i_p]
# set_property IOSTANDARD LVDS_25 [get_ports tx1_sync_i_p]
# set_property PACKAGE_PIN AJ8 [get_ports {rxp_in_0[0]}]
# set_property PACKAGE_PIN AC4 [get_ports {rxp_in_1[0]}]
set_property PACKAGE_PIN AJ8 [get_ports {rxp_in_0[0]}]
set_property PACKAGE_PIN AG8 [get_ports {rxp_in_0[1]}]
set_property PACKAGE_PIN AH10 [get_ports {rxp_in_0[2]}]
set_property PACKAGE_PIN AE8 [get_ports {rxp_in_0[3]}]


create_clock -period 4.000 -name gt_clk_i_p -waveform {0.000 2.000} [get_ports gt_clk_i_p]
